Accounts/urls.py
from django.urls import path
from Accounts.views import user_login, user_register, user_logout

app_name = 'accounts'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', user_register, name='register'),
    path('logout/', user_logout, name='logout'),
]

Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls', namespace='home')),
    path('accounts/', include('Accounts.urls', namespace='accounts')),
    path('movies', include('Movies.urls', namespace='movies')),
]

Home/urls.py
from django.urls import path
from .views import home, john_mc, about

app_name = 'home'

urlpatterns = [
     path('', home, name='home'),
     path('continue/', john_mc, name='john'),
     path('about/', about, name='about'),
]

Movies/urls.py
from django.urls import path
from Movies.views import movies_list, movie_details

app_name = 'movies'

urlpatterns = [
    path('list/', movies_list, name='movies_list'),
    path('details/<int:pk>/<slug:slug>/', movie_details, name='movie_details'),
]

Accounts/models.py
from django.db import models

# Create your models here.

Home/models.py
from django.db import models

# Create your models here.

Movies/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse


class TimeStampMixin(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# class PublishPostManager(models.Manager):
#     get_queryset(self):
#         return super().get_queryset().filter(status = 'publish')

class Movies(TimeStampMixin):
    STATUS = (
        ('publish', 'Publish'),
        ('draft', 'Draft'),
    )
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120, unique=True)
    year = models.PositiveIntegerField()
    genres = models.CharField(max_length=70)
    director = models.CharField(max_length=70)
    stars = models.CharField(max_length=120)
    rate = models.FloatField(null=True, blank=True)
    storyline = RichTextUploadingField()
    certificate = models.CharField(max_length=10, null=True, blank=True)
    status = models.CharField(choices=STATUS, default='draft', max_length=30)

    def __str__(self):
        return '{}'.format(self.title)

    def get_absolute_url(self):
        return reverse('movie_details', args=[self.pk, self.slug])

    class Meta:
        verbose_name = 'Movie'

Accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))


class UserRegisterForm(forms.Form):
    username = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    email = forms.EmailField(max_length=50, widget=forms.EmailInput({'placeholder': 'Email'}))
    password1 = forms.CharField(label='Password', max_length=30, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label='Confirm Password', max_length=30, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))

    # Check The Email Address If Already Have Existed.
    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email)
        if user.exists():
            raise forms.ValidationError('This Email Already Exists!')
        return email

    # Check Password Confirm.
    def clean(self):
        clean_data = super().clean()
        p1 = clean_data.get('password1')
        p2 = clean_data.get('password2')
        if p1 and p2:
            if p1 != p2:
                raise forms.ValidationError("Password Doesn't Match!")

    # Check Username If Already Have Existed.
    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username)
        if user.exists():
            raise forms.ValidationError('This Username Already Exists!')
        return username

Accounts/views.py
from django.shortcuts import render, redirect
from Accounts.forms import UserLoginForm, UserRegisterForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib import messages


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'You Are Successfully Logged In. ', 'success')
                return redirect(to='home:home')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password1'])
            messages.success(request, 'Congrats Your Account Is Created!', 'success')
            return redirect(to='accounts:login')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'Thank You For Spending Some Quality Time With My Blog Today.', 'success')
    return redirect(to='home:home')

Home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/home.html')


def john_mc(request):
    return render(request, 'home/johnmc.html')


def about(request):
    return render(request, 'home/about.html')

Movies/views.py
from django.shortcuts import render, get_list_or_404
from Movies.models import Movies


def movies_list(request):
    movies = Movies.objects.all()
    context = {'movies': movies}
    return render(request, 'movies/movies_list.html', context=context)


def movie_details(request, pk, slug):
    details = get_list_or_404(Movies, pk=pk, slug=slug)
    context = {'details': details}
    return render(request, 'movies/movie_details.html', context=context)

Accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block context %}
    <form action="." method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

Accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block context %}
    <form action="." method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register" class="btn btn-dark">
    </form>
{% endblock %}

Home/templates/home/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    About
{% endblock %}

{% block navbar %}
 {% include 'navbar.html' %}
{% endblock %}

{% block context %}
    This Is A Simple Personal Blog Page.
    <br>
    Just For Fun!
{% endblock %}

Home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
 {% include 'navbar.html' %}
{% endblock %}

{% block context %}
<h2 class="mb-5 tm-content-title">
    What Are<br>Artificial Intelligence<br>Machine Learning<br>Deep Learning?
</h2>
<p class="mb-5">
    Artificial intelligence (AI), machine learning and deep learning are three terms often used interchangeably to describe software that behaves intelligently. However, it is useful to understand the key distinctions among them.
    You can think of deep learning, machine learning and artificial intelligence as a set of Russian dolls nested within each other, beginning with the smallest and working out. Deep learning is a subset of machine learning, and machine learning is a subset of AI, which is an umbrella term for any computer program that does something smart. In other words, all machine learning is AI, but not all AI is machine learning, and so forth.
</p>
<hr class="mb-5">
<p class="mb-5">
    <img src="{% static "img/John_McCarthy.jpg" %}" alt="John McCarthy">
<br>
John McCarthy, widely recognized as one of the godfathers of AI, defined it as “the science and engineering of making intelligent machines.
</p>
<a href="{% url "home:john" %}" class="btn btn-primary">Continue...</a>
{% endblock %}

Home/templates/home/johnmc.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    John McCarthy
{% endblock %}


{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}


{% block context %}
    <img src="{% static "img/John_McCarthy_Stanford.jpg" %}" alt="John McCarthy" style="width:500px;height:600px;">
    <br>
    <br>
    <p>
        John McCarthy (September 4, 1927 – October 24, 2011) was an American computer scientist and cognitive scientist. McCarthy was one of the founders of the discipline of artificial intelligence.
        He coined the term "artificial intelligence"
        (AI) developed the Lisp programming language family, significantly influenced the design of the ALGOL programming language,
        popularized time-sharing, invented garbage collection, and was very influential in the early development of AI.
        McCarthy spent most of his career at Stanford University.
        He received many accolades and honors, such as the 1971 Turing Award for his contributions to the topic of AI,
        the United States National Medal of Science, and the Kyoto Prize.
    </p>
{% endblock %}

Movies/templates/movies/movie_details.html
{% extends 'base.html' %}

{% block title %}
    Movie Details
{% endblock %}

{% block context %}
    {% for each in details %}
        Name : {{ each.title}}
        <br>
        Year : {{ each.year }}
        <br>
        Genres : {{ each.genres }}
        <br>
        Director : {{ each.director }}
        <br>
        Stars : {{ each.stars }}
        <br>
        Rate : {{ each.rate }}
        <br>
        Certificated Parents Guide : {{ each.certificate }}
        <br>
        Story Line : {{ each.storyline|safe }}
    {% endfor %}
{% endblock %}

{% block navbar %}
 {% include 'navbar.html' %}
{% endblock %}

Movies/templates/movies/movies_list.html
{% extends 'base.html' %}

{% block title %}
    Movies List
{% endblock %}

{% block context %}
    {% for each in movies %}
        <a href="{{ each.get_absolute_url }}">{{ each.title }}</a>
        <br>
    {% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>
        {% block title %}
            Personal Blog
        {% endblock %}
    </title>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet" /> <!-- https://fonts.google.com/ -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" /> <!-- https://getbootstrap.com/ -->
    <link href="{% static "fontawesome/css/all.min.css" %}" rel="stylesheet" /> <!-- https://fontawesome.com/ -->
    <link href="{% static "css/templatemo-diagoona.css" %}" rel="stylesheet" />
<!--
-->
</head>

<body>
    <div class="tm-container">
    {% include 'messages.html' %}
        <div>
            <div class="tm-row pt-4">
                <div class="tm-col-left">
                    <div class="tm-site-header media">
                        <i class="fas fa-umbrella-beach fa-3x mt-1 tm-logo"></i>
                        <div class="media-body">
                            <h1 class="tm-sitename text-uppercase">
                                Artificial Intelligence<br>Machine Learning<br>Deep Learning
                            </h1>
                            <p class="tm-slogon">Welcome To The New World !</p>
                        </div>
                    </div>
                </div>
            </div>

                {% block navbar %}
                {% endblock %}

            <div class="tm-row">
                <div class="tm-col-left"></div>
                <main class="tm-col-right">
                    <section class="tm-content">

                        {% block context %}
                        {% endblock %}

                    </section>
                </main>
            </div>
        </div>

        <div class="tm-row">
            <div class="tm-col-left text-center">
                <ul class="tm-bg-controls-wrapper">
                    <li class="tm-bg-control active" data-id="0"></li>
                    <li class="tm-bg-control" data-id="1"></li>
                    <li class="tm-bg-control" data-id="2"></li>
                </ul>
            </div>
            <div class="tm-col-right tm-col-footer">
                <footer class="tm-site-footer text-right">
                    <p class="mb-0">Copyright 2020 Diagoona Co.

                    | Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-text-link">TemplateMo</a></p>
                </footer>
            </div>
        </div>

        <!-- Diagonal background design -->
        <div class="tm-bg">
            <div class="tm-bg-left"></div>
            <div class="tm-bg-right"></div>
        </div>
    </div>

    <script src={% static "js/jquery-3.4.1.min.js" %}></script>
    <script src=>{% static "js/bootstrap.min.js" %}</script>
    <script src={% static "js/jquery.backstretch.min.js" %}></script>
    <script src={% static "js/templatemo-script.js" %}></script>
</body>
</html>

templates/messages.html
{% if messages %}
    {% for each in messages %}
        <p>{{ each }}</p>
    {% endfor %}
{% endif %}

templates/navbar.html
   <div class="tm-col-right">
        <nav class="navbar navbar-expand-lg" id="tm-main-nav">
            <button class="navbar-toggler toggler-example mr-0 ml-auto" type="button"
                    data-toggle="collapse" data-target="#navbar-nav"
                    aria-controls="navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span><i class="fas fa-bars"></i></span>
            </button>
            <div class="collapse navbar-collapse tm-nav" id="navbar-nav">
                <ul class="navbar-nav text-uppercase">
                    <li class="nav-item active">
                        <a class="nav-link tm-nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link tm-nav-link" href="{% url 'home:about' %}">About</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link tm-nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link tm-nav-link" href="{% url 'movies:movies_list' %}">Movies</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link tm-nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link tm-nav-link" href="{% url 'accounts:register' %}">Registration</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>